# Generated by Django 5.2.6 on 2026-04-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='membershipstatuslog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipstatuslog',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='clubs.membership'),
        ),
        migrations.AddField(
            model_name='membershipstatuslog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('organization', 'member', 'club')},
        ),
        migrations.AddIndex(
            model_name='membershipstatuslog',
            index=models.Index(fields=['organization', 'membership', 'effective_date'], name='clubs_membe_organiz_60054a_idx'),
        ),
    ]
