# Generated by Django 5.2.6 on 2026-04-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(max_length=64)),
                ('effective_date', models.DateField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_transfer_changes', to=settings.AUTH_USER_MODEL)),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='clubs.club')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='clubs.department')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='clubs.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='clubs.club')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='clubs.department')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'membership', 'effective_date'], name='clubs_membe_organiz_a647c5_idx')],
            },
        ),
    ]
