# Generated by Django 5.2.6 on 2026-04-02 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('tenancy', '0002_tenantconfigversion_change_diff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('commission_accrual', 'Commission accrual'), ('settlement_generated', 'Settlement generated'), ('withdrawal_approved', 'Withdrawal approved'), ('withdrawal_rejected', 'Withdrawal rejected')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('reference_type', models.CharField(max_length=64)),
                ('reference_id', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('generated_at', models.DateTimeField()),
                ('hold_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('on_hold', 'On hold'), ('releasable', 'Releasable'), ('closed', 'Closed')], default='on_hold', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=24)),
                ('requires_reviewer_approval', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['organization', 'model_type', 'effective_from'], name='finance_com_organiz_daf0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['organization', 'effective_to'], name='finance_com_organiz_c91d9d_idx'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='withdrawalblacklist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='withdrawalblacklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_blacklist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['organization', 'occurred_at'], name='finance_led_organiz_672c97_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['organization', 'entry_type', 'occurred_at'], name='finance_led_organiz_bf5042_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['organization', 'reference_type', 'reference_id'], name='finance_led_organiz_d05eee_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['organization', 'generated_at'], name='finance_set_organiz_634279_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['organization', 'hold_until'], name='finance_set_organiz_b6ea82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('organization', 'period_year', 'period_month')},
        ),
        migrations.AddIndex(
            model_name='withdrawalblacklist',
            index=models.Index(fields=['organization', 'is_active'], name='finance_wit_organiz_fa3d1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='withdrawalblacklist',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['organization', 'requester', 'requested_at'], name='finance_wit_organiz_76bafb_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['organization', 'status', 'requested_at'], name='finance_wit_organiz_1a4b82_idx'),
        ),
    ]
