# Generated by Django 5.2.6 on 2026-04-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(blank=True, max_length=255)),
                ('style', models.CharField(blank=True, max_length=255)),
                ('medium', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('copyright_status', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
            ],
            options={
                'unique_together': {('organization', 'external_id')},
            },
        ),
    ]
