# Generated by Django 5.2.6 on 2026-04-02 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('tenancy', '0002_tenantconfigversion_change_diff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAssetVersionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=16)),
                ('change_reason', models.CharField(max_length=128)),
                ('snapshot', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ContentChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContentChapterACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_type', models.CharField(choices=[('role', 'Role'), ('user', 'User')], max_length=8)),
                ('principal_value', models.CharField(max_length=64)),
                ('can_view', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contentasset',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentasset',
            name='allow_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='contentasset',
            index=models.Index(fields=['organization', 'state'], name='content_con_organiz_242ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='contentasset',
            index=models.Index(fields=['organization', 'title'], name='content_con_organiz_038c5a_idx'),
        ),
        migrations.AddField(
            model_name='contentassetversionlog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_logs', to='content.contentasset'),
        ),
        migrations.AddField(
            model_name='contentassetversionlog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_version_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentassetversionlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='contentchapter',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.contentasset'),
        ),
        migrations.AddField(
            model_name='contentchapter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='contentchapteracl',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_entries', to='content.contentchapter'),
        ),
        migrations.AddField(
            model_name='contentchapteracl',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddIndex(
            model_name='contentassetversionlog',
            index=models.Index(fields=['organization', 'asset', 'version'], name='content_con_organiz_94acd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentassetversionlog',
            unique_together={('organization', 'asset', 'version')},
        ),
        migrations.AddIndex(
            model_name='contentchapter',
            index=models.Index(fields=['organization', 'asset', 'order_index'], name='content_con_organiz_abf41a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentchapter',
            unique_together={('organization', 'asset', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='contentchapteracl',
            index=models.Index(fields=['organization', 'chapter'], name='content_con_organiz_6cb2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='contentchapteracl',
            index=models.Index(fields=['organization', 'principal_type', 'principal_value'], name='content_con_organiz_aba28a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentchapteracl',
            unique_together={('organization', 'chapter', 'principal_type', 'principal_value')},
        ),
    ]
