# Generated by Django 5.2.6 on 2026-04-02 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentassetversionlog_contentchapter_and_more'),
        ('tenancy', '0002_tenantconfigversion_change_diff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentasset',
            name='storage_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='ContentDownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('token_hint', models.CharField(max_length=16)),
                ('purpose', models.CharField(choices=[('download', 'Download'), ('share', 'Share')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='content.contentasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_download_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_path', models.CharField(max_length=512)),
                ('artifact_path', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=64)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='content.contentasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_artifacts', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='content.contentdownloadtoken')),
            ],
        ),
        migrations.CreateModel(
            name='ContentEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('subscription', 'Subscription'), ('redeem_code', 'Redeem code')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('redeem_code_id', models.BigIntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='content.contentasset')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_content_entitlements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentRedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('code_last4', models.CharField(max_length=4)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeem_codes', to='content.contentasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content_codes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_content_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentDownloadRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=32)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_request_logs', to='content.contentasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_download_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'user', 'requested_at'], name='content_con_organiz_a6884c_idx'), models.Index(fields=['organization', 'asset', 'requested_at'], name='content_con_organiz_059589_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contentdownloadtoken',
            index=models.Index(fields=['organization', 'user', 'expires_at'], name='content_con_organiz_b23d10_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdownloadtoken',
            index=models.Index(fields=['organization', 'asset', 'expires_at'], name='content_con_organiz_92ad22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentdownloadtoken',
            unique_together={('organization', 'token_hash')},
        ),
        migrations.AddIndex(
            model_name='contentartifact',
            index=models.Index(fields=['organization', 'asset', 'created_at'], name='content_con_organiz_b2dd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='contentartifact',
            index=models.Index(fields=['organization', 'user', 'created_at'], name='content_con_organiz_c2a807_idx'),
        ),
        migrations.AddIndex(
            model_name='contententitlement',
            index=models.Index(fields=['organization', 'user', 'asset', 'is_active'], name='content_con_organiz_811649_idx'),
        ),
        migrations.AddIndex(
            model_name='contententitlement',
            index=models.Index(fields=['organization', 'source', 'is_active'], name='content_con_organiz_6b68f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contententitlement',
            unique_together={('organization', 'user', 'asset', 'source')},
        ),
        migrations.AddIndex(
            model_name='contentredeemcode',
            index=models.Index(fields=['organization', 'asset', 'expires_at'], name='content_con_organiz_2df91d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentredeemcode',
            index=models.Index(fields=['organization', 'redeemed_at'], name='content_con_organiz_6dce43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentredeemcode',
            unique_together={('organization', 'code_hash')},
        ),
    ]
