# Generated by Django 5.2.6 on 2026-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('handler', models.CharField(max_length=255)),
                ('interval_seconds', models.PositiveIntegerField(default=300)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['is_enabled', 'next_run_at'], name='scheduler_s_is_enab_118412_idx')],
            },
        ),
    ]
