# Generated by Django 5.2.6 on 2026-04-02 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='US', max_length=2)),
                ('capacity_limit', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_group_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickup_points', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GroupLeaderOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=16)),
                ('document_title', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=64)),
                ('document_reference', models.CharField(max_length=255)),
                ('document_metadata', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_onboarding_applications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leader_onboarding_applications', to=settings.AUTH_USER_MODEL)),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_onboarding_applications', to='logistics.pickuppoint')),
            ],
        ),
        migrations.CreateModel(
            name='PickupPointBusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='logistics.pickuppoint')),
            ],
        ),
        migrations.CreateModel(
            name='PickupPointClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='logistics.pickuppoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=models.Index(fields=['organization', 'state', 'city'], name='logistics_p_organiz_c9db32_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=models.Index(fields=['organization', 'assigned_group_leader'], name='logistics_p_organiz_716675_idx'),
        ),
        migrations.AddIndex(
            model_name='groupleaderonboarding',
            index=models.Index(fields=['organization', 'applicant', 'status'], name='logistics_g_organiz_599c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupleaderonboarding',
            index=models.Index(fields=['organization', 'status', 'submitted_at'], name='logistics_g_organiz_028429_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuppointbusinesshour',
            index=models.Index(fields=['organization', 'pickup_point', 'weekday'], name='logistics_p_organiz_0b0cda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickuppointbusinesshour',
            unique_together={('organization', 'pickup_point', 'weekday')},
        ),
        migrations.AddIndex(
            model_name='pickuppointclosure',
            index=models.Index(fields=['organization', 'pickup_point', 'starts_at'], name='logistics_p_organiz_7136cf_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuppointclosure',
            index=models.Index(fields=['organization', 'pickup_point', 'ends_at'], name='logistics_p_organiz_e3b6b8_idx'),
        ),
    ]
