# Generated by Django 5.2.6 on 2026-04-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_pickuppoint_groupleaderonboarding_and_more'),
        ('tenancy', '0002_tenantconfigversion_change_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='restricted_handling_flags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='location',
            name='temperature_zone',
            field=models.CharField(choices=[('ambient', 'Ambient'), ('controlled', 'Controlled'), ('chilled', 'Chilled'), ('frozen', 'Frozen')], default='ambient', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('organization', 'warehouse', 'name')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'zone'], name='logistics_l_organiz_299128_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'temperature_zone'], name='logistics_l_organiz_d098d9_idx'),
        ),
    ]
