# Generated by Django 5.2.6 on 2026-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0003_location_restricted_handling_flags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuppoint",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="encrypted_address_line1",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="encrypted_address_line2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="encrypted_city",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="encrypted_contact_phone",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="encrypted_country",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="encrypted_postal_code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="encrypted_state",
            field=models.TextField(blank=True, default=""),
        ),
    ]
