# Generated by Django 5.2.6 on 2026-04-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=128)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(default='success', max_length=32)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('before_data', models.JSONField(default=dict)),
                ('after_data', models.JSONField(default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenancy.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='observabili_organiz_62cd29_idx'), models.Index(fields=['action', 'created_at'], name='observabili_action_628550_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_key', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics_snapshots', to='tenancy.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'metric_key', 'captured_at'], name='observabili_organiz_8053e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='tenancy.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status', 'created_at'], name='observabili_organiz_cc8d68_idx')],
            },
        ),
    ]
