# Generated by Django 5.2.6 on 2026-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportexport",
            name="report_metadata",
            field=models.JSONField(default=dict),
        ),
    ]
