# Generated by Django 5.2.6 on 2026-04-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcheckin',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventcheckin',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddIndex(
            model_name='eventcheckin',
            index=models.Index(fields=['organization', 'event', 'checked_in_at'], name='events_even_organiz_ef9de1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('organization', 'event', 'member')},
        ),
    ]
