# Generated by Django 5.2.6 on 2026-04-02 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_membershiptransferlog'),
        ('events', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendanceReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('mark_checked_in', 'Mark checked in'), ('remove_check_in', 'Remove check-in')], max_length=32)),
                ('reason_code', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_key', models.CharField(max_length=128)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventcheckin',
            unique_together={('organization', 'event', 'member')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'club', 'starts_at'], name='events_even_organiz_2a215c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcheckin',
            index=models.Index(fields=['organization', 'member', 'checked_in_at'], name='events_even_organiz_38e766_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['organization', 'event', 'registered_at'], name='events_even_organiz_a653b7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['organization', 'member', 'registered_at'], name='events_even_organiz_e98953_idx'),
        ),
        migrations.AddField(
            model_name='eventattendancereconciliation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventattendancereconciliation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendancereconciliation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='eventattendancereconciliation',
            name='reconciled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_reconciliation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventresourcedownload',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_downloads', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventresourcedownload',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_resource_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventresourcedownload',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='tenancy.organization'),
        ),
        migrations.AddIndex(
            model_name='eventattendancereconciliation',
            index=models.Index(fields=['organization', 'event', 'reconciled_at'], name='events_even_organiz_e9fafe_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendancereconciliation',
            index=models.Index(fields=['organization', 'member', 'reconciled_at'], name='events_even_organiz_4719ad_idx'),
        ),
        migrations.AddIndex(
            model_name='eventresourcedownload',
            index=models.Index(fields=['organization', 'event', 'downloaded_at'], name='events_even_organiz_2679b3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventresourcedownload',
            index=models.Index(fields=['organization', 'member', 'downloaded_at'], name='events_even_organiz_502a88_idx'),
        ),
        migrations.AddIndex(
            model_name='eventresourcedownload',
            index=models.Index(fields=['organization', 'event', 'resource_key'], name='events_even_organiz_9cb811_idx'),
        ),
    ]
