# Generated by Django 5.2.6 on 2026-04-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfigversion',
            name='change_diff',
            field=models.JSONField(default=dict),
        ),
    ]
